name: Deploy

on:
  deployment:

env:
  SERVICE_NAME: openchecklistproject-site
  VERSION: ${{ github.event.deployment.ref }}

jobs:
  start:
    name: Start deployment
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/set-deployment-status@v1
        name: "Deployment: In Progress"
        with:
          deployment_id: ${{ github.event.deployment.id }}
          state: in_progress
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_APP_TOKEN }}

  docker-tag-latest:
    name: Tag docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - env:
          NEW_TAG: latest
        run: |
          docker pull picklewagon/${SERVICE_NAME:?}:${VERSION:?}
          docker tag picklewagon/${SERVICE_NAME}:${VERSION} picklewagon/${SERVICE_NAME}:${NEW_TAG}
          docker push picklewagon/${SERVICE_NAME}:${NEW_TAG}

  finalize:
    name: Finalize deployment
    runs-on: ubuntu-latest
    needs: docker-tag-latest
    steps:
      - uses: avakar/set-deployment-status@v1
        name: "Deployment: Failed"
        if: failure()
        with:
          deployment_id: ${{ github.event.deployment.id }}
          state: failure
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_APP_TOKEN }}
      - uses: avakar/set-deployment-status@v1
        name: "Deployment: Success"
        if: success()
        with:
          deployment_id: ${{ github.event.deployment.id }}
          state: success
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_APP_TOKEN }}
